import type { Locale } from "./i18n";

const ES: Record<string, string> = {
  Brazil: "Brasil",
  Italy: "Italia",
  Spain: "España",
  "United States": "Estados Unidos",
  Mexico: "México",
  Netherlands: "Países Bajos",
  Germany: "Alemania",
  France: "Francia",
  England: "Inglaterra",
  Belgium: "Bélgica",
  Turkey: "Turquía",
  "Saudi Arabia": "Arabia Saudita",
  Peru: "Perú",
  Greece: "Grecia",
  Switzerland: "Suiza",
  Russia: "Rusia",
  Ukraine: "Ucrania",
  Scotland: "Escocia",
  Denmark: "Dinamarca",
  Sweden: "Suecia",
  Poland: "Polonia",
  Croatia: "Croacia",
  Japan: "Japón",
  Qatar: "Catar",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  Cyprus: "Chipre",
  Norway: "Noruega",
  Canada: "Canadá",
  Hungary: "Hungría",
  "Czech Republic": "Chequia",
  Romania: "Rumania",
  Slovenia: "Eslovenia",
  Slovakia: "Eslovaquia",
  Belarus: "Bielorrusia",
  Kazakhstan: "Kazajistán",
  Egypt: "Egipto",
  "South Korea": "Corea del Sur",
  "Korea, South": "Corea del Sur",
  Malaysia: "Malasia",
  Thailand: "Tailandia",
  Wales: "Gales",
  Ireland: "Irlanda",
  "Northern Ireland": "Irlanda del Norte",
  Finland: "Finlandia",
  Iceland: "Islandia",
  Azerbaijan: "Azerbaiyán",
  "Bosnia-Herzegovina": "Bosnia y Herzegovina",
  "North Macedonia": "Macedonia del Norte",
  Luxembourg: "Luxemburgo",
  Lithuania: "Lituania",
  Latvia: "Letonia",
  Moldova: "Moldavia",
  Morocco: "Marruecos",
  Tunisia: "Túnez",
  Algeria: "Argelia",
  "South Africa": "Sudáfrica",
  Panama: "Panamá",
  "Dominican Republic": "República Dominicana",
  "Trinidad and Tobago": "Trinidad y Tobago",
  "New Zealand": "Nueva Zelanda",
  Singapore: "Singapur",
  Uzbekistan: "Uzbekistán",
  Iran: "Irán",
  Iraq: "Irak",
  Oman: "Omán",
  Bahrain: "Baréin",
  Jordan: "Jordania",
  Lebanon: "Líbano",
  Argentina: "Argentina",
  "other / not covered": "otros / sin cobertura",
};

/** Country name for the reader: the source's English name, translated where the Spanish differs. */
export function countryName(locale: Locale, name: string | null | undefined): string {
  if (!name) return "";
  return locale === "es" ? (ES[name] ?? name) : name;
}
