select
    player_id::int                                   as tm_player_id,
    name                                             as full_name,
    {{ norm_name('name') }}                          as name_norm,
    {{ safe_date('date_of_birth') }}                 as dob,
    country_of_citizenship,
    country_of_birth,
    city_of_birth,
    position,
    sub_position,
    foot,
    {{ safe_numeric('height_in_cm') }}               as height_cm,
    nullif(current_club_id, '')::int                 as current_club_id,
    current_club_name,
    current_club_domestic_competition_id             as current_club_competition_id,
    {{ safe_numeric('market_value_in_eur') }}        as market_value_eur,
    {{ safe_numeric('highest_market_value_in_eur') }} as highest_market_value_eur,
    nullif(international_caps, '')::int              as international_caps,
    nullif(international_goals, '')::int             as international_goals,
    current_national_team_id,
    nullif(last_season, '')::int                     as last_season,
    {{ safe_date('contract_expiration_date') }}      as contract_expiration_date,
    url                                              as tm_url,
    snapshot_date
from {{ source('raw_tm', 'players') }}
