name: albiceleste
version: "0.1.0"
config-version: 2
profile: albiceleste

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: target
clean-targets: [target, dbt_packages]

models:
  albiceleste:
    +persist_docs: {relation: true, columns: true}
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: marts
      +materialized: table

seeds:
  albiceleste:
    +schema: seeds
